### ISSUE TITLE
NEW: agregar campo identification al modelo Client

### ISSUE THREAD

**Issue by lufe089** [lufe089/CORINFront-end#12]
Actualizar también tabla en draw.io
Modelo en django
Serializer en django
View en django ( si aplica)
Front-end para pedir el dato.

**Comment by zalonore** [comment]
Se creo el campo en el modelo, se actualizó el servicio y la semilla (Para el Backend).
Se actualizaron los modals para manejar el campo identificación, en la creación y edición. Se organizó la vista para muestre el campo y también la exportación del cliente.
